Logical: CaseSurveillanceMpoxCIF
Title: "Case surveillance: Mpox (CIF)"
Parent: BackboneElement
* enrollmentDate 1..1 date "Date of notification."
* incidentDate 0..1 date "."
* uniqueCaseId 0..1 string "Two letter country code, case number (e.g., AB001, AB002) or national case ID if already assigned."
* clusterNumberIdIfApplicable 0..1 string "Two letter country code, cluster number, case number, (e.g., AB.01.001, AB.02.001) or national cluster number/ID if already assigned"
* nameOfDataCollector 0..1 string "MPOX CS: Name of data collector"
* dataCollectorRole 0..1 string "MPOX CS: Data collector role"
* dataCollectorInstitution 0..1 string "MPOX CS: Data collector institution"
* dataCollectorTelephoneNumber 0..1 string "MPOX CS: Data collector telephone number"
* dataCollectorEmail 0..1 string "MPOX CS: Data collector email"
* formCompletionDate 0..1 date "MPOX CS: Form completion date"
* caseClassification 0..1 code "Classification of the case"
* caseClassification from MPOXCSCaseClassificationCRFVS (required)
* dateOfDiagnosis 0..1 date "First date of clinical or lab diagnosis"
* currentStatus 0..1 code "MPOX CS: Current Status"
* currentStatus from MPOXCSCurrentStatusVS (required)
* firstName 0..1 string "First name"
* lastName 0..1 string "Family name or last name of the patient of case."
* dateOfBirth 0..1 date "Date of birth. This field can also be used when the date of birth is estimated, in conjunction with another TEA that indicates whether the birth date is estimated."
* dateOfBirthUnknown 0..1 boolean "MPOX CS: Date of birth - Unknown"
* ageYears 0..1 unsignedInt "Age of case in years (report 0 if &lt; 1 year)"
* ageMonths 0..1 positiveInt "MPOX CS: Age (months)"
* ageDays 0..1 positiveInt "MPOX CS: Age (days)"
* weightInGrams 0..1 positiveInt "MPOX CS: Weight in grams"
* heightInCm 0..1 positiveInt "MPOX CS: Height in cm"
* midUpperCircumferenceMuac 0..1 positiveInt "MPOX CS: Mid-upper circumference (MUAC)"
* isTheChildMalnourished 0..1 code "If age &lt;5 years, is the child malnourished? "
* isTheChildMalnourished from MPOXCSYesNoUnknownVS (required)
* sex 0..1 code "Sex at birth"
* sex from MPOXCSSexVS (required)
* specifyOtherSexAtBirth 0..1 string "MPOX CS: Specify other sex at birth"
* gender 0..1 code "MPOX CS: Gender"
* gender from MPOXCSGenderVS (required)
* specifyOtherGender 0..1 string "MPOX CS: Specify other gender"
* sexualBehavior 0..1 code "Sexual behavior of the case"
* sexualBehavior from MPOXCSSexualBehaviorVS (required)
* specifyOtherSexualOrientation 0..1 string "MPOX CS: Specify other sexual orientation"
* individualSNationalIdentificationNumberIfApplicable 0..1 string "MPOX CS: Individual’s national identification number (if applicable):"
* countryOfResidence 0..1 code "Person&#x27;s country of residence."
* countryOfResidence from GENCountriesVS (required)
* telephoneNumber 0..1 string "MPOX CS: Telephone number"
* email 0..1 string "E-mail address for the patient or case."
* address 0..1 string "MPOX CS: Address"
* whatIsTheOccupationOfTheCase 0..1 string "MPOX CS: Occupation of the case"
* isThisCaseAHealthcareWorker 0..1 code "Is the case a healthcare worker?"
* isThisCaseAHealthcareWorker from MPOXCSYesNoUnknownVS (required)
* isTheCaseASexWorker 0..1 code "MPOX CS: Sex worker"
* isTheCaseASexWorker from MPOXCSYesNoUnknownVS (required)
* isTheCaseAnInternallyDisplacedPersonOrARefugee 0..1 code "MPOX CS: IDP or refugee"
* isTheCaseAnInternallyDisplacedPersonOrARefugee from MPOXCSYesNoUnknownVS (required)
* livingInAnInternallyDisplacedPeopleSIdpOrRefugeeCamp 0..1 code "MPOX CS: Living in IDP or refugee camp?"
* livingInAnInternallyDisplacedPeopleSIdpOrRefugeeCamp from MPOXCSYesNoUnknownVS (required)
* nameOfTheCamp 0..1 string "MPOX CS: Name of the camp"
* nameOfHealthCareCentre 0..1 string "MPOX CS: Name of health-care centre"
* typeOfHealthcareCentre 0..1 string "MPOX CS: Type of healthcare centre"
* nameOfTreatingPhysician 0..1 string "MPOX CS: Name of treating physician"
* telephone 0..1 string "MPOX CS: Telephone of treating physician"
* adress 0..1 string "MPOX CS: Adress of treating physician"
* clinicalAndVaccinationInformation 0..1 ClinicalAndVaccinationInformation "Clinical and vaccination information"
* exposureToProbableOrConfirmedCase 0..1 ExposureToProbableOrConfirmedCase "Exposure to probable or confirmed case"
* exposureEvents 0..* ExposureEvents "Exposure events"
* exposureInHouseholdSetting 0..1 ExposureInHouseholdSetting "Exposure in household setting"
* occupationalExposureInHealthcareSettings 0..1 OccupationalExposureInHealthcareSettings "Occupational exposure in healthcare settings"
* sexualActivity 0..1 SexualActivity "Sexual activity"
* sexualPartners 0..* SexualPartners "Sexual partners"
* travelHistory 0..* TravelHistory "Travel history"
* animalExposure 0..* AnimalExposure "Animal exposure"
* mostLikelyModeOfTransmission 0..1 MostLikelyModeOfTransmission "Most likely mode of transmission"
* diseaseSeverityAndOutcome 0..1 DiseaseSeverityAndOutcome "Disease severity and outcome"
* diagnosticPathogenTesting 0..* DiagnosticPathogenTesting "Diagnostic/Pathogen testing"
* forwardTracing 0..1 ForwardTracing "Forward tracing"
* contactDetails 0..* ContactDetails "Contact details"
